"""drop product_info table

Revision ID: 15531c0ecd6e
Revises: 1459161ce827
Create Date: 2025-07-05 13:22:03.780906

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15531c0ecd6e'
down_revision: Union[str, Sequence[str], None] = '1459161ce827'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_info')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_info',
    sa.Column('info_id', sa.INTEGER(), nullable=False),
    sa.Column('variant_id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=False),
    sa.Column('text', sa.VARCHAR(), nullable=False),
    sa.Column('show_on_site', sa.BOOLEAN(), nullable=False),
    sa.Column('info_type', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], ),
    sa.PrimaryKeyConstraint('info_id', 'variant_id')
    )
    # ### end Alembic commands ###
