"""Add updated_at to pricing and stock tables

Revision ID: 45361e0813fd
Revises: 64f8153136e7
Create Date: 2025-07-05 13:57:56.597125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45361e0813fd'
down_revision: Union[str, Sequence[str], None] = '64f8153136e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # SQLite doesn't support adding NOT NULL columns with non-constant defaults
    # So we add as nullable first, update values, then make NOT NULL
    
    # Add columns as nullable
    op.add_column('variant_pricing', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('variant_stock', sa.Column('updated_at', sa.DateTime(), nullable=True))
    
    # Set default values for existing rows
    op.execute("UPDATE variant_pricing SET updated_at = CURRENT_TIMESTAMP WHERE updated_at IS NULL")
    op.execute("UPDATE variant_stock SET updated_at = CURRENT_TIMESTAMP WHERE updated_at IS NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('variant_stock', 'updated_at')
    op.drop_column('variant_pricing', 'updated_at')
    # ### end Alembic commands ###
