"""Add variant attributes table

Revision ID: 4ab70f905c07
Revises: 45361e0813fd
Create Date: 2025-07-05 16:18:41.042633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ab70f905c07'
down_revision: Union[str, Sequence[str], None] = '45361e0813fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('variant_attributes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('variant_id', sa.Integer(), nullable=False),
    sa.Column('attribute_type', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('is_filter', sa.Boolean(), nullable=False),
    sa.Column('display', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_variant_attributes_name_value', 'variant_attributes', ['name', 'value'], unique=False)
    op.create_index('idx_variant_attributes_variant_id', 'variant_attributes', ['variant_id'], unique=False)
    op.create_index(op.f('ix_variant_attributes_id'), 'variant_attributes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_variant_attributes_id'), table_name='variant_attributes')
    op.drop_index('idx_variant_attributes_variant_id', table_name='variant_attributes')
    op.drop_index('idx_variant_attributes_name_value', table_name='variant_attributes')
    op.drop_table('variant_attributes')
    # ### end Alembic commands ###
