"""add product_info table

Revision ID: 966cfec4c78d
Revises: c53cbb8c52f2
Create Date: 2025-07-05 13:10:51.919466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '966cfec4c78d'
down_revision: Union[str, Sequence[str], None] = 'c53cbb8c52f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('variant_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('show_on_site', sa.Boolean(), nullable=False),
    sa.Column('info_type', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_info_id'), 'product_info', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_info_id'), table_name='product_info')
    op.drop_table('product_info')
    # ### end Alembic commands ###
