"""Add product info table

Revision ID: ce38d9aea784
Revises: 4ab70f905c07
Create Date: 2025-07-05 16:24:11.788213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce38d9aea784'
down_revision: Union[str, Sequence[str], None] = '4ab70f905c07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('info_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('info_type', sa.String(), nullable=False),
    sa.Column('show_on_site', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_product_info_product_id', 'product_info', ['product_id'], unique=False)
    op.create_index('idx_product_info_type', 'product_info', ['info_type'], unique=False)
    op.create_index(op.f('ix_product_info_id'), 'product_info', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_info_id'), table_name='product_info')
    op.drop_index('idx_product_info_type', table_name='product_info')
    op.drop_index('idx_product_info_product_id', table_name='product_info')
    op.drop_table('product_info')
    # ### end Alembic commands ###
